name: Build Electron App

on:
  workflow_dispatch:

jobs:
  build:

    strategy:
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Build React
        run: npm run build

      - name: Build Electron
        env:
            CSC_IDENTITY_AUTO_DISCOVERY: false
        run: npm run dist -- --publish=never

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: release/**